name: Vanilla Pico
id: vanilla-pico

stages:
- id: build
  base: scratch
  singlelayer: true
  labels:
    maintainer: Vanilla OS Contributors
  adds:
    rootfs/vanilla-pico.tar.zst: /
  cmd: ["/bin/bash"]
