name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install debootstrap
        run: |
            sudo apt-get update
            sudo apt-get install -y debootstrap

      - name: Build Rootfs
        working-directory: rootfs
        run: |
          sudo apt install -y podman
          sudo bash build.sh
          cp vanilla-pico.tar.zst vanilla-pico-${{ matrix.arch }}.tar.zst

      - uses: actions/upload-artifact@v7
        with:
          name: vanilla-pico-rootfs-${{ matrix.arch }}
          path: rootfs/vanilla-pico-${{ matrix.arch }}.tar.zst

      - uses: vanilla-os/vib-gh-action@v1.1.0

      - uses: actions/upload-artifact@v7
        with:
          name: Containerfile
          path: Containerfile
          overwrite: true

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # Allow actions to create release
      attestations: write # To create and write attestations
      id-token: write # Additional permissions for the persistence of the attestations

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v8
        with:
          name: Containerfile

      - uses: actions/download-artifact@v8
        with:
          path: rootfs
          pattern: vanilla-pico-rootfs-*
          merge-multiple: true

      - name: Create Checksums
        working-directory: rootfs
        run: sha256sum vanilla-pico-*.tar.zst > checksums.txt

      - name: Create Release
        working-directory: rootfs
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes vanilla-pico-*.tar.zst checksums.txt

      - name: Upload Containerfile to Release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.ref_name }}" Containerfile

      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'Containerfile, rootfs/vanilla-pico-*.tar.zst, rootfs/checksums.txt'
